import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("data.csv")
print(data)
print(data.head(3))
print(data.shape)
print(data.columns.tolist())
print(data["score"])
print(data["city"])
print("how many people:", len(data))
print("average score:",data["score"].mean())
print("highest score:",data["score"].max())
print("lowest score:",data["score"].min())
top=data["score"].idxmax()
print("top scorer:",data.loc[top,"name"])
high = data[data["score"]>80]
print(high)
print("how many scored above 80:",len(high))
print(data.groupby("city")["score"].mean())
plt.bar(data["name"],data["score"])
plt.title("scores by person")
plt.xlabel("name")
plt.ylabel("score")
plt.savefig("chart.png")
plt.show()
data=pd.read_csv("messy.csv")
print(data.isnull().sum())